server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://noiwuigpzqizth:82843c29a0cbb93f41373c769f45948619b72ab6865bcaf4fbecc995e3ee715b@ec2-174-129-225-160.compute-1.amazonaws.com:5432/deg59t5tefmk1h
    username: noiwuigpzqizth
    password: 82843c29a0cbb93f41373c769f45948619b72ab6865bcaf4fbecc995e3ee715b
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
